-- Seed reference data for prescription safety (development — clinically review before production).

INSERT INTO drug_reference (generic_name, drug_class, common_brand_names_india, pediatric_approved, notes, search_text)
VALUES
    ('Paracetamol', 'analgesic_antipyretic', ARRAY['Crocin', 'Calpol', 'Dolo'], true, NULL,
     'Paracetamol Crocin Calpol Dolo analgesic antipyretic'),
    ('Ibuprofen', 'NSAID', ARRAY['Brufen', 'Combiflam'], true, NULL,
     'Ibuprofen Brufen Combiflam NSAID'),
    ('Amoxicillin', 'antibiotic', ARRAY['Mox', 'Novamox'], true, NULL,
     'Amoxicillin Mox Novamox antibiotic'),
    ('Amoxicillin-Clavulanate', 'antibiotic', ARRAY['Augmentin', 'Clavam'], true, NULL,
     'Amoxicillin-Clavulanate Augmentin Clavam antibiotic'),
    ('Azithromycin', 'antibiotic', ARRAY['Azithral', 'Zithromax'], true, NULL,
     'Azithromycin Azithral Zithromax antibiotic'),
    ('Cefixime', 'antibiotic', ARRAY['Taxim-O', 'Zifi'], true, NULL,
     'Cefixime Taxim-O Zifi antibiotic'),
    ('Ondansetron', 'antiemetic', ARRAY['Emeset', 'Vomikind'], true, NULL,
     'Ondansetron Emeset Vomikind antiemetic'),
    ('Domperidone', 'antiemetic', ARRAY['Domstal', 'Vomistop'], true, 'QT prolongation risk with some macrolides.',
     'Domperidone Domstal Vomistop antiemetic'),
    ('Cetirizine', 'antihistamine', ARRAY['Cetzine', 'Alerid'], true, NULL,
     'Cetirizine Cetzine Alerid antihistamine'),
    ('Levocetirizine', 'antihistamine', ARRAY['Levocet', 'Xyzal'], true, NULL,
     'Levocetirizine Levocet Xyzal antihistamine'),
    ('Montelukast', 'leukotriene_antagonist', ARRAY['Montair', 'Asthalin Montair'], true, NULL,
     'Montelukast Montair leukotriene'),
    ('Salbutamol', 'bronchodilator', ARRAY['Asthalin', 'Ventorlin'], true, NULL,
     'Salbutamol Asthalin Ventorlin bronchodilator'),
    ('ORS', 'rehydration', ARRAY['Electral', 'ORSL'], true, NULL,
     'ORS Electral ORSL rehydration'),
    ('Zinc Sulphate', 'supplement', ARRAY['Zincovit', 'Z&D'], true, NULL,
     'Zinc Sulphate Zincovit supplement'),
    ('Iron supplements', 'supplement', ARRAY['Ferium', 'Maltofer'], true, NULL,
     'Iron supplements Ferium Maltofer'),
    ('Metronidazole', 'antibiotic', ARRAY['Flagyl', 'Metrogyl'], true, NULL,
     'Metronidazole Flagyl Metrogyl antibiotic'),
    ('Diphenhydramine', 'antihistamine', ARRAY['Benadryl'], true, 'Sedating antihistamine.',
     'Diphenhydramine Benadryl antihistamine'),
    ('Promethazine', 'antihistamine', ARRAY['Phenergan'], true, 'Sedation risk.',
     'Promethazine Phenergan antihistamine'),
    ('Ranitidine', 'H2_blocker', ARRAY['Rantac'], false, 'Largely withdrawn; prefer alternatives.',
     'Ranitidine Rantac H2 blocker'),
    ('Omeprazole', 'PPI', ARRAY['Omez'], true, NULL,
     'Omeprazole Omez PPI'),
    ('Loperamide', 'antidiarrheal', ARRAY['Imodium'], true, 'Caution in pediatrics; avoid under 2 years.',
     'Loperamide Imodium antidiarrheal'),
    ('Dicyclomine', 'antispasmodic', ARRAY['Cyclopam'], true, 'Contraindicated under 6 months.',
     'Dicyclomine Cyclopam antispasmodic'),
    ('Mefenamic acid', 'NSAID', ARRAY['Meftal-P'], true, NULL,
     'Mefenamic acid Meftal-P NSAID'),
    ('Aspirin', 'NSAID', ARRAY['Ecosprin'], true, 'Avoid in children except specific indications.',
     'Aspirin Ecosprin NSAID')
ON CONFLICT (generic_name) DO NOTHING;

INSERT INTO drug_interactions (drug_a_generic, drug_b_generic, severity, mechanism, clinical_effect, management, source)
VALUES
    ('Aspirin', 'Ibuprofen', 'major',
     'NSAID competition for COX-1',
     'Ibuprofen may reduce aspirin antiplatelet effect if given together.',
     'Separate dosing; avoid routine co-administration.',
     'BNFc 2024'),
    ('Azithromycin', 'Domperidone', 'moderate',
     'Both prolong QT interval',
     'Increased risk of QT prolongation and arrhythmia.',
     'Avoid combination when possible; consider alternative antiemetic.',
     'BNFc 2024'),
    ('Domperidone', 'Ondansetron', 'moderate',
     'Additive QT prolongation',
     'Increased QT prolongation risk.',
     'Use one antiemetic; monitor if both required.',
     'BNFc 2024'),
    ('Cetirizine', 'Promethazine', 'minor',
     'Additive CNS depression',
     'Increased sedation and drowsiness.',
     'Avoid combination at bedtime unless clinically indicated.',
     'BNFc 2024'),
    ('Amoxicillin-Clavulanate', 'Iron supplements', 'minor',
     'Chelation / absorption interference',
     'Reduced absorption of both if taken together.',
     'Separate by at least 2 hours.',
     'BNFc 2024'),
    ('Cefixime', 'Iron supplements', 'minor',
     'Chelation',
     'Reduced cefixime absorption if co-administered.',
     'Separate by at least 2 hours.',
     'BNFc 2024'),
    ('Loperamide', 'Promethazine', 'contraindicated',
     'Opioid-like effects + sedation in pediatrics',
     'Risk of ileus, respiratory depression in children.',
     'Avoid in pediatric patients.',
     'BNFc 2024')
ON CONFLICT (drug_a_generic, drug_b_generic) DO NOTHING;

-- DOSAGE VALUES ARE SEED DATA FOR DEVELOPMENT. MUST BE CLINICALLY REVIEWED BEFORE PRODUCTION.
INSERT INTO pediatric_dosage_reference (
    generic_name, route, min_age_months, max_age_months,
    dose_per_kg_mg, frequency_per_day_min, frequency_per_day_max,
    max_single_dose_mg, max_daily_dose_mg, source, notes
)
VALUES
    ('Paracetamol', 'oral', 1, 216, 15.000, 4, 6, 500.00, 60.00, 'WHO Model Formulary for Children',
     'max_daily_dose_mg is per kg per day cap'),
    ('Ibuprofen', 'oral', 6, 216, 10.000, 3, 4, 400.00, 40.00, 'BNFc 2024',
     'max_daily_dose_mg is per kg per day'),
    ('Amoxicillin', 'oral', 1, 216, 25.000, 3, 3, 500.00, 75.00, 'BNFc 2024',
     'Typical 25 mg/kg/dose TDS'),
    ('Azithromycin', 'oral', 6, 216, 10.000, 1, 1, 500.00, 10.00, 'BNFc 2024',
     'Once daily'),
    ('Cetirizine', 'oral', 24, 216, NULL, 1, 1, 10.00, 10.00, 'BNFc 2024',
     'Fixed dose for older children'),
    ('Domperidone', 'oral', 12, 216, 0.300, 3, 3, 10.00, 0.90, 'BNFc 2024',
     'mg/kg per dose'),
    ('Ondansetron', 'oral', 1, 216, 0.150, 2, 3, 8.00, 24.00, 'BNFc 2024',
     'mg/kg per dose'),
    ('Salbutamol', 'inhaled', 1, 216, NULL, 2, 4, NULL, NULL, 'BNFc 2024',
     'Nebulizer dosing varies'),
    ('Loperamide', 'oral', 24, 216, NULL, 2, 2, 2.00, 4.00, 'BNFc 2024',
     'Not for under 2 years'),
    ('Dicyclomine', 'oral', 6, 216, NULL, 3, 3, 10.00, 30.00, 'BNFc 2024',
     'Contraindicated under 6 months');
